language: ruby
bundler_args: "--without system_tests"
script:
- bundle exec rake
cache: bundler
sudo: true
rvm:
- 2.1.0
before_install:
- gem update --system 2.1.11
- gem --version
env:
- CHEF_VERSION="= 11.18.12"
- CHEF_VERSION="= 12.4.1"

notifications:
  slack:
    secure: Kqp/g7ta+JzAklXhTIl+ZU+FqrdXJe7DNWuqDZXec4YLLB9pFR1MpUyW1kx+WBcb7Fc//w4Q+1NLn02Slg9ay1xkRkNVi1UInUk89ocqwPbsmESA/690fnRba+C7mW/6D3Z+C7AMPQeZszhcRVzX1xrH3b3xlvLMvyFk/UnQOMU=
